# Site settings
title: Kata Tech Life
header-img: img/galaxy.jpg
email: kata.choi@gmail.com
copyright_name: Katat Choi
# description: "I am a full stack javascript developer, specializing in Node.JS/Angular.JS/Ionic/Cordova/Docker etc.., experiencing in building web/mobile products from scratch for startups. I love learning new technologies and taking challenges."
baseurl: ""
url: "http://katat.github.io"
twitter_username: katat
github_username:  katat
facebook_username:  katat
email_username:  kata.choi@gmail.com

# Build settings
comments: true
kramdown:
  input: GFM
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-sitemap]
